server.port=7084
file.rootAddress=../../PF_Storage/
file.userAddress=../../PF_Storage/UserProject/
file.reqModelDir=req_model
file.devModelDir=dev_model
file.downloadRootAddress=../../PF_Storage/Download/
file.pfRootAddress=../../PF_Storage/pf/
file.owlRootAddress=../../PF_Storage/owl/
file.pOwlRootAddress=../../PF_Storage/powl/
file.eOwlRootAddress=../../PF_Storage/eowl/
file.tmpRootAddress=../../PF_Storage/tmp/
file.lastestProjectAddress=../../PF_Storage/latest/